### ISSUE TITLE
Tags in Post Meta

### ISSUE THREAD

**Issue by RaitisSevelis** [wpbakery/visual-composer-theme#103]
I have tags instead of data in Post Meta (in search, categories, and exact post, and also comments). Also, need to check other places to fix it. See screenshot in attachment.

![post-meta-failure](https://cloud.githubusercontent.com/assets/6083905/24645445/cf1f2984-1920-11e7-8d19-66ce895bd2cd.png)

**Comment by veidenbaums** [comment]
Fix #115
