### ISSUE TITLE
In Posts No Comments and Footer

### ISSUE THREAD

**Issue by RaitisSevelis** [wpbakery/visual-composer-theme#104]
I don't see comments and footer in a post (when opened). 

Footer and comments are enabled.

**Comment by RaitisSevelis** [comment]
Fatal error: Call to undefined function wpcom_vip_get_adjacent_post() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/single.php on line 38

**Comment by veidenbaums** [comment]
Fixed #115
