### ISSUE TITLE
PHP Warning. WP Debug Enabled

### ISSUE THREAD

**Issue by RaitisSevelis** [wpbakery/visual-composer-theme#106]
Warning: Missing argument 2 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510

Warning: Missing argument 3 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510

Warning: Missing argument 4 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510

Warning: Missing argument 5 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510

Warning: Missing argument 6 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510

Warning: Missing argument 7 for visualcomposerstarter_give_linked_images_class() in /Users/raitissevelis/Sites/wp-content/themes/visual-composer-theme-ver-1.2/functions.php on line 510
Art Exhibition of City An art museum or art gallery is a building or space for the exhibition of art, usually visual art. Museums can be public or private, but what distinguishes a museum is the ownership of a collection. Although primarily concerned with providing a space to show works of visual art, art galleries are [...]

**Comment by veidenbaums** [comment]
Fix for missing arguments #115
