### ISSUE TITLE
Steal _s' tests

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-theme#60]
https://github.com/Automattic/_s/blob/master/.travis.yml

**Comment by szepeviktor** [comment]
Thanks.
Please turn on Travis too.

**Comment by mmihey** [comment]
@szepeviktor Builds are working https://travis-ci.org/wpbakery/visual-composer-theme but failing now.

**Comment by szepeviktor** [comment]
OK!
