### ISSUE TITLE
Main js

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-theme#63]
Please consider calling `functions.js` main.js as it is self-executing.

**Comment by RaitisSevelis** [comment]
@Bathead please include this in 1.2 as well

**Comment by AngeIII** [comment]
@szepeviktor actually, after checking the WordPress default themes and WordPress core code we can confirm that there are no self-executing javascript files from the theme.
There is only one point to name the file as `functions.js` to follow the logic from `functions.php`
