### ISSUE TITLE
Support a child theme

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-theme#64]
Please consider supporting a child theme for those who are not able to develop a complete theme.

**Comment by szepeviktor** [comment]
And include and example please.

**Comment by RaitisSevelis** [comment]
https://blog.visualcomposer.io/wp-content/uploads/2017/03/visual-composer-child-theme.zip

**Comment by szepeviktor** [comment]
Thank you.

There are invalid quotes in this ZIP: `’`
