### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-theme#71]
Please generate theme pot file with WP core tools.
https://github.com/WordPress/wordpress-develop/tree/master/tools/i18n

**Comment by RaitisSevelis** [comment]
As a user, I want to be able to use Starter theme as a multi-language theme. Ensure compatibility with WPML, qTranslate-x and WPML.

**Comment by cstibi** [comment]
and compotibility with Polylang Free ;)

**Comment by RaitisSevelis** [comment]
qTranslate X: ok

**Comment by RaitisSevelis** [comment]
WPML: We will forward it to WPML team to ensure compatibility once merged into ver 1.2

**Comment by RaitisSevelis** [comment]
Bug: @Bathead if Polylang is activated I don't see main menu and header widget area any more.

**Comment by AngeIII** [comment]
@RaitisSevelis what about WPML? maybe we can contact them to make theme compatible?

**Comment by veidenbaums** [comment]
@AngeIII the theme will be ready for WPML review today, need to change the text domain and some other small issues before that.
