### ISSUE TITLE
Improve front page view when no posts and search page results

### ISSUE THREAD

**Issue by AngeIII** [wpbakery/visual-composer-theme#88]
Currently, if a page doesn't have posts it show button "read more" this is wrong.
![ladning-page-empty](https://cloud.githubusercontent.com/assets/3625675/22591173/d012d1b2-ea1b-11e6-8133-fff28b299630.png)
![search-results](https://cloud.githubusercontent.com/assets/3625675/22591172/d0129ba2-ea1b-11e6-9577-bde2624da192.png)

**Comment by RaitisSevelis** [comment]
@Bathead could you please handle this one as well within 1.2

**Comment by RaitisSevelis** [comment]
@Bathead I still see this problem. How to replicate:

1) Delete all posts you have
2) in Customizer set Frontpage - Static Frontpage ->  Your latest posts
3) See preview with some Read More button and no content
