### ISSUE TITLE
Is WPBakery Visual Composer compatible with php 5.6?

### ISSUE THREAD

**Issue by heenaI** [wpbakery/visual-composer-theme#89]
Hi There, 
I have to update my website to php 5.6 and I get this error from php compatibilty checker.

FILE: /www/htdocs/w0107da1/eumssi/wp-content/plugins/js_composer/js_composer.php
----------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------
 220 | ERROR | Visibility for magic method __sleep must be public. Found: private
----------------------------------------------------------------------------------

I am not sure if this is compatible with php 5. has anyone already done this?

**Comment by AngeIII** [comment]
@heenaI yes, it works perfectly with php 5.6.

**Comment by heenaI** [comment]
@AngeIII  thanks I will try to update
